title: Filthy Hacker
description: "Filthy Hacker es un blog dedicado al hacking. ¿Te apasiona la ciberseguridad, o quieres aprender? ¡Este es el lugar! Resolución de máquinas, explicación de vulnerabilidades, CTF's y varias temáticas relacionadas al hacking." 
author:
  name: "m4teo"
  email: "mandinoparedes@hotmail.com"
  url: "https://mateonitro550.github.io"

baseurl: "/"
newbaseurl: "js"

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap


# Custom variables
owner : "m4teo"
year : "2022"
google_analytics: UA-219710333-2
