title: Filthy Hacker
description: "A Blog For Filthy Hackers"
author:
  name: "m4teo"
  email: "mandinoparedes@hotmail.com"
  url: "https://mateonitro550.github.io"

baseurl: "/"
newbaseurl: "js"

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap


# Custom variables
owner : "m4teo"
year : "2022"
google_analytics: UA-219710333-2
