title: Filthy Hacker
description: "Filthy Hacker is a blog dedicated to hacking. Passionate about cybersecurity or eager to learn? This is the place! Machine walkthroughs, vulnerability breakdowns, CTF challenges, and more."

author:
  name: "Mateo Andino"
  url: "https://mateonitro550.github.io"

baseurl: "/"
source: .
destination: ./_site
permalink: /:title/

collections_dir: _posts

collections:
  en:
    output: true
    permalink: /:collection/:title/
  es:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: "_en"
      type: "en"
    values:
      layout: "post"
  - scope:
      path: "_es"
      type: "es"
    values:
      layout: "post"

pagination:
  enabled: true
  per_page: 5
  permalink: "/:collection/page/:num/"
  sort_field: "date"
  sort_reverse: true

future: true

plugins:
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-sitemap

google_analytics: G-524F5BE8G5

owner : "MateoNitro550"
year : "2025"
